### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by junhyeokkang** [kaist-dmlab/TCLP#13]
Can you introduce other datasets applicable to your algorithm?

**Comment by YoojuShin** [comment]
We can apply TCLP to other time series dataset such as Opportunity dataset([link](https://archive.ics.uci.edu/ml/datasets/opportunity+activity+recognition)) and Breakfast dataset ([link](https://serre-lab.clps.brown.edu/resource/breakfast-actions-dataset/)).
